name: Deploy Node.js CI

on:
  push:
    #      branches: [ "main" ]
    tags: # Remove the `branches` node and add this one
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
    - run: npm ci
    - run: npm run build --if-present
    - uses: actions/upload-artifact@v3
      with:
        name: Build
        path: dist
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    needs: build

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: Build
          path: build
      - run: zip -r build.zip build/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build.zip"
